## Waylon Walker's hub-and-spoke
bind-key W popup -E -w 80% -h 80% "tmux new-session -A -s sigil_org 'cd ~/git/sarumont.github.io && nvim'"
bind-key O popup -E -w 80% -h 80% "tmux new-session -A -s moov_second_brain 'cd ~/My\\ Drive/notes/moov-second-brain && nvim MOC.md'"
bind-key N popup -E -w 80% -h 80% "tmux new-session -A -s second_brain 'cd ~/second-brain && nvim Dump.md'"
bind-key A popup -E -w 80% -h 80% "tmux new-session -A -s dotfiles 'cd ~/git/dotfiles && nvim'"

## tmux session navigation
bind C-g new-window -n "git-session-picker" "ta ~/git"
bind C-w new-window -n "work-session-picker" "ta ~/work"
