import = [
    "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[font]
size = 11.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Fira Mono"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"
