import = [
    "~/.config/alacritty/onenord.toml"
]

[font]
size = 11.0

[font.bold]
family = "MonaspiceNe NFP"
style = "Bold"

[font.bold_italic]
family = "MonaspiceNe NFP"
style = "Bold Italic"

[font.italic]
family = "MonaspiceNe NFP"
style = "Italic"

[font.normal]
family = "MonaspiceNe NF"
style = "Regular"
