## Waylon Walker's hub-and-spoke
bind-key W popup -E -w 80% -h 80% "tmux new-session -A -s sigil_org 'cd $REPO_GALLERY_DIR/sarumont.github.io && nvim'"
bind-key O popup -E -w 80% -h 80% "tmux new-session -A -s moov_second_brain 'cd ~/My\\ Drive/notes/moov-second-brain && nvim MOC.md'"
bind-key N popup -E -w 80% -h 80% "tmux new-session -A -s second_brain 'cd ~/second-brain && nvim Dump.md'"
bind-key A popup -E -w 80% -h 80% "tmux new-session -A -s dotfiles 'cd $REPO_GALLERY_DIR/dotfiles && nvim'"

## new worktree session from any session
bind-key T popup -E -w 80% -h 80% "twt --pick"

## tmux session navigation
bind C-g new-window -n "git-session-picker" "ta $REPO_GALLERY_DIR"
bind C-w new-window -n "work-session-picker" "ta $WORK_GALLERY_DIR"
