format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_state\
    $git_status\
    $package\
    $dotnet\
    $golang\
    $java\
    $nodejs\
    $python\
    $ruby\
    $rust\
    $nix_shell\
    $conda\
    $memory_usage\
    $aws\
    $kubernetes\
    $gcloud\
    $env_var\
    $cmd_duration\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
"""

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[env_var.PGDATABASE]
format = '$symbol [$env_value]($style) '
symbol = ''
style = 'grey bold'

[gcloud]
format = '[$symbol$project]($style) '
style = 'bold yellow'
