k9s:
  refreshRate: 2
  logBufferSize: 1000
  logRequestSize: 200
  currentContext: cf_k8s_rk
  currentCluster: cf_k8s_rk
  clusters:
    cf_k8s_rk:
      namespace:
        active: all
        favorites:
        - all
        - default
      view:
        active: po
