## Waylon Walker's hub-and-spoke
bind-key W popup -E -w 80% -h 80% "tmux new-session -A -s sigil_org 'cd ~/git/sarumont.github.io && nvim'"
bind-key N popup -E -w 80% -h 80% "tmux new-session -A -s second_brain 'cd ~/second-brain && nvim Dump.md'"
bind-key A popup -E -w 80% -h 80% "tmux new-session -A -s dotfiles 'cd ~/git/dotfiles && nvim'"

## tmux session navigation
bind C-g new-window -n "git-session-picker" "ta ~/git"
